import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Dots from '../components/Dots'
import ExploreButton from '../components/ExploreButton'
import NumberedButton from '../components/NumberedButton'
import NumberedTitle from '../components/NumberedTitle'
import PrimaryNavigation from '../components/PrimaryNavigation'
import Tabs from '../components/Tabs'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    // <div className="container flex">
    //   <div className="box"><h1>a</h1></div>
    //   <div className="box"><NumberedTitle number="2" text="example" /></div>
    //   <div className="box"><ExploreButton /></div>
    //   <div className="box">d</div>
    //   <div className="box"><PrimaryNavigation /></div>
    //   <div className="box"><Tabs /></div>
    //   <div className="box"><Dots /></div>
    //   <div className="box flow">
    //     <NumberedButton selected>1</NumberedButton>
    //     <NumberedButton selected={false}>2</NumberedButton>
    //   </div>
    // </div>
    <>
      <header className="primaryHeader flex">
        <div>
          <Image className="logo" src="/assets/shared/logo.svg" alt="space tourism logo" width="20" height="20" />
        </div>
        <PrimaryNavigation />
      </header>

      <div className="container">
        <h1 className="text-accent fs-500 ff-sans-cond uppercase letter-spacing-1">So, you want to travel to
        <span className="fs-900 ff-serif text-white">Space</span></h1>
        <p>Let’s face it; if you want to go to space, you might as well genuinely go to 
        outer space and not hover kind of on the edge of it. Well sit back, and relax 
        because we’ll give you a truly out of this world experience!</p>

        <ExploreButton />
      </div>
    </>
  )
}

export default Home
