import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Dots from '../components/Dots'
import ExploreButton from '../components/ExploreButton'
import NumberedTitle from '../components/NumberedTitle'
import PrimaryNavigation from '../components/PrimaryNavigation'
import Tabs from '../components/Tabs'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
    <div className="container flex">
      <div className="box"><h1>a</h1></div>
      <div className="box"><NumberedTitle number="2" text="example" /></div>
      <div className="box"><ExploreButton /></div>
      <div className="box">d</div>
      <div className="box"><PrimaryNavigation /></div>
      <div className="box"><Tabs /></div>
      <div className="box"><Dots /></div>
    </div>
  )
}

export default Home
